name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      ado_jfrog_platform_url:
        description: 'Enter the JFrog Platform URL'
        required: true
      ado_jfrog_platform_username:
        description: 'Enter the JFrog Platform Username'
        required: true
      ado_jfrog_platform_password:
        description: 'Enter the JFrog Platform Password'
        required: true
      ado_jfrog_platform_docker_domain:
        description: 'Enter the JFrog Platform Docker Domain'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          ADO_JFROG_PLATFORM_URL: ${{ inputs.ado_jfrog_platform_url }}
          ADO_JFROG_PLATFORM_USERNAME: ${{ inputs.ado_jfrog_platform_username }}
          ADO_JFROG_PLATFORM_PASSWORD: ${{ inputs.ado_jfrog_platform_password }}
          ADO_JFROG_PLATFORM_DOCKER_DOMAIN: ${{ inputs.ado_jfrog_platform_docker_domain }}
