name: Node.js CI

on:
  push:
    branches:
      - github-actions-tests
  pull_request:
    branches:
      - github-actions-tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          ADO_JFROG_PLATFORM_URL: ${{ secrets.PLATFORM_URL }}
